import uuid
import datetime
from sqlalchemy.orm import Session
from app.models import LetterDraftModel, EventModel

def generate_reference_number(issue_type: str) -> str:
    year = datetime.datetime.now().year
    code = "GEN"
    if "pothole" in issue_type.lower() or "damaged" in issue_type.lower():
        code = "GCC/RD-MAINT"
    elif "water" in issue_type.lower() or "flood" in issue_type.lower():
        code = "GCC/SWD-FLOOD"
    elif "traffic" in issue_type.lower() or "congestion" in issue_type.lower():
        code = "GCTP/TRAFFIC-OPS"
    elif "electric" in issue_type.lower() or "wire" in issue_type.lower():
        code = "TANGEDCO/GRID-SAFETY"
    elif "critical" in issue_type.lower() or "accident" in issue_type.lower():
        code = "RGGGH/EMS-TRAUMA"
    
    unique_suffix = uuid.uuid4().hex[:6].upper()
    return f"{code}/{year}/{unique_suffix}"

def create_letter_draft_for_event(event_dict: dict, db: Session = None) -> dict:
    """
    Generate an official government letter/complaint draft for an urban event.
    """
    issue_type = event_dict.get("issue_type", "Road Defect")
    severity = event_dict.get("severity", "MEDIUM")
    vehicle_id = event_dict.get("vehicle_id", "BUS-021")
    lat = event_dict.get("latitude", 13.0827)
    lng = event_dict.get("longitude", 80.2707)
    confidence = event_dict.get("confidence", 0.92)
    details = event_dict.get("details", "Road condition flagged by onboard dashcam Edge AI.")
    now_str = datetime.datetime.now().strftime("%d %B %Y, %I:%M %p")
    
    ref_no = generate_reference_number(issue_type)
    
    # Customize based on issue category
    if "pothole" in issue_type.lower() or "damaged" in issue_type.lower():
        dept = "Greater Chennai Corporation - Road Maintenance & Bridges Department"
        recipient_name = "The Executive Engineer (Roads & Bridges)"
        recipient_address = "Works Department, Greater Chennai Corporation, Ripon Building, EVR Periyar Salai, Chennai - 600003"
        subject = f"OFFICIAL CIVIC COMPLAINT: Urgent Asphalt Resurfacing & Road Hazard Rectification ({ref_no})"
        statutory_ref = "Section 197 of the Chennai City Municipal Corporation Act, 1919 & IRC:82-2015 Road Safety Guidelines"
        requested_action = "Deploy road maintenance rapid-patching crew with cold-mix bituminous asphalt within 48-hour municipal SLA. Erect caution cones immediately."
        letter_body = f"""Respected Sir/Madam,

Sub: Urgent civic grievance and requisition for immediate repair of road surface defect detected by Smart City Mobile Transit Sensing Fleet.

This is an automated formal notice generated by the Urban Intelligence Monitoring Network operating aboard the Greater Chennai public bus fleet.

1. OBSERVATION SUMMARY:
   During regular scheduled transit route operations, the vehicle-mounted Edge AI Computer Vision unit on bus [{vehicle_id}] detected a severe road defect categorized as '{issue_type}' (AI Confidence: {confidence*100:.1f}%).

2. GEO-LOCATION & TELEMETRY:
   - Coordinates: Latitude {lat:.5f}, Longitude {lng:.5f}
   - Time of Detection: {now_str}
   - Severity Level: {severity}
   - Field Inspection Note: {details}

3. CIVIC SAFETY & LEGAL CONTEXT:
   Pursuant to {statutory_ref}, arterial municipal corridors must be maintained in a motorable, pothole-free condition to prevent two-wheeler accidents, tire punctures, and pedestrian fatalities.

4. REQUISITION:
   You are respectfully requested to instruct the concerned Zonal Assistant Engineer to inspect the site and complete bituminous patch repairs within the designated 48-hour SLA period.

Yours faithfully,
Office of Urban Mobility & Smart City Infrastructure Monitoring Cell
Greater Chennai Corporation
"""
        channel = "E_GOVERNANCE_PORTAL"

    elif "water" in issue_type.lower() or "flood" in issue_type.lower():
        dept = "Greater Chennai Corporation - Storm Water Drainage & Flood Control Wing"
        recipient_name = "The Superintending Engineer (Storm Water Drains)"
        recipient_address = "Special Projects & SWD Directorate, Ripon Building, Greater Chennai Corporation, Chennai - 600003"
        subject = f"EMERGENCY INUNDATION ADVISORY: Road Waterlogging & Drainage Clearance Requisition ({ref_no})"
        statutory_ref = "Disaster Management Act, 2005 (Monsoon Readiness) & GCC Monsoon Standing Operating Procedures"
        requested_action = "Mobilize mobile de-watering diesel pump units, clear stormwater culvert inlets of silt/debris, and inspect subterranean conduits within 6 hours."
        letter_body = f"""Respected Sir/Madam,

Sub: Immediate drainage clearance and stormwater de-watering requisition for inundated transit route.

This is an urgent operational dispatch from the Urban Mobility Sensing Network operating across Chennai.

1. INCIDENT REPORT:
   Sensing Vehicle [{vehicle_id}] has recorded significant water accumulation ({issue_type}) causing vehicle lane constriction and pedestrian stranding.

2. LOCALIZATION DATA:
   - Precise Coordinates: Latitude {lat:.5f}, Longitude {lng:.5f}
   - Timestamp: {now_str}
   - Severity Assessment: {severity}
   - Visual Analysis Note: {details}

3. MUNICIPAL MANDATE:
   In accordance with {statutory_ref}, immediate mitigation is required to avoid prolonged road foundation damage and traffic standstill along this transit corridor.

4. RECOMMENDED MEASURES:
   - Deploy motorized suction pumps to drain standing water.
   - De-silt adjacent catch-pits and storm drain inlets.
   - Provide road barrier warnings if depth exceeds 15 cm.

Yours faithfully,
Central Municipal Urban Intelligence Desk
Greater Chennai Corporation
"""
        channel = "E_GOVERNANCE_PORTAL"

    elif "electric" in issue_type.lower() or "wire" in issue_type.lower():
        dept = "Tamil Nadu Generation and Distribution Corporation (TANGEDCO)"
        recipient_name = "The Superintending Engineer (Distribution & Safety)"
        recipient_address = "TANGEDCO Central Division, 144 Anna Salai, Chennai - 600002"
        subject = f"CRITICAL HAZARD DIRECTIVE: Snapped Overhead Power Cable / Electrical Sparking ({ref_no})"
        statutory_ref = "Central Electricity Authority (Safety & Electric Supply) Regulations, 2023 - Section 73"
        requested_action = "Execute immediate remote 11kV/22kV feeder circuit isolation and dispatch rapid breakdown emergency line crew within 1 hour."
        letter_body = f"""URGENT & CONFIDENTIAL - PUBLIC SAFETY EMERGENCY

To,
{recipient_name}
{recipient_address}

Sub: CRITICAL ALERT - Snapped live conductor / active electrical hazard on public roadway detected by transit camera.

1. CRITICAL INCIDENT LOG:
   Public transit sensing vehicle [{vehicle_id}] has captured an active high-voltage electrical hazard ({issue_type}) posing an immediate threat of electrocution to pedestrians and motorists.

2. INCIDENT SITE TELEMETRY:
   - Coordinates: Latitude {lat:.5f}, Longitude {lng:.5f}
   - Observed At: {now_str}
   - Severity: CRITICAL
   - Camera Evidence: {details}

3. MANDATORY SAFETY MEASURES:
   Under {statutory_ref}, immediate isolation of the relevant transformer/feeder line is mandated.

4. DISPATCH INSTRUCTIONS:
   - Immediately verify grid feeder status for this sector.
   - Coordinate with local Traffic Police to cordon off a 50-meter radius.
   - Dispatch the emergency repair truck without delay.

By Order,
Integrated Command & Control Center (ICCC)
Urban Hazard Response Cell
"""
        channel = "EMERGENCY_DISPATCH_SMS_AND_PORTAL"

    elif "critical" in issue_type.lower() or "accident" in issue_type.lower():
        dept = "Rajiv Gandhi Government General Hospital (RGGGH) Trauma & Emergency Medical Services"
        recipient_name = "The Chief Medical Officer & Casualty Medical Officer"
        recipient_address = "Emergency Trauma Care Center, Rajiv Gandhi Government General Hospital, EVR Salai, Park Town, Chennai - 600003"
        subject = f"EMERGENCY TRAUMA NOTIFICATION: Severe Road Incident Ambulance Dispatch Order ({ref_no})"
        statutory_ref = "National Highway Trauma Care & Golden Hour Emergency Medical Protocol"
        requested_action = "Initiate immediate 108 Advanced Life Support (ALS) Ambulance mobilization to incident GPS. Prepare trauma resuscitation team."
        letter_body = f"""EMERGENCY RESUSCITATION DIRECTIVE

To,
{recipient_name}
{recipient_address}

Sub: Urgent Road Collision with Casualty Risk - Automated Trauma Notification & Golden Hour Response.

1. INCIDENT TELEMETRY:
   - Location Coordinates: Latitude {lat:.5f}, Longitude {lng:.5f}
   - Reporting Transit Bus: {vehicle_id}
   - Timestamp: {now_str}
   - Incident Classification: {issue_type} (SEVERITY: CRITICAL)
   - AI Visual Context: {details}

2. STATUTORY PROTOCOL:
   Under the {statutory_ref}, timely intervention during the 'Golden Hour' is paramount to casualty survival.

3. DISPATCH REQUISITION:
   - Dispatch nearest 108 Advanced Life Support Ambulance with oxygen and trauma stabilization kits.
   - Put Level-1 Trauma Emergency OT on standby.
   - Alert City Traffic Police for green corridor transit.

Official Hospital Dispatch Desk,
Smart City Emergency Services Integration Node
"""
        channel = "AUTOMATED_CALL_AND_DISPATCH"

    else:
        dept = "Greater Chennai Traffic Police - Operations & Traffic Control Cell"
        recipient_name = "The Deputy Commissioner of Police (Traffic Planning)"
        recipient_address = "Greater Chennai Traffic Police Headquarters, Vepery High Road, Chennai - 600007"
        subject = f"TRAFFIC BOTTLENECK DIRECTIVE: Severe Congestion & Lane Blockage Report ({ref_no})"
        statutory_ref = "Section 115 of the Motor Vehicles Act, 1988 (Regulation of Traffic)"
        requested_action = "Deploy traffic beat constables for manual junction phase regulation and remove illegal curb parking or disabled vehicles."
        letter_body = f"""Respected Sir,

Sub: Traffic bottleneck and congestion advisory generated by public bus fleet telemetry.

1. TRAFFIC FLOW DATA:
   Sensing transit bus [{vehicle_id}] moving along this corridor has reported severe vehicle stagnation and slow transit speeds.
   - Coordinates: Latitude {lat:.5f}, Longitude {lng:.5f}
   - Recorded At: {now_str}
   - Density Assessment: {severity}
   - Telemetry Notes: {details}

2. REQUISITION:
   Kindly deploy traffic personnel to clear corridor bottlenecks and synchronize traffic signal cycles to restore smooth bus transit.

Yours faithfully,
Metropolitan Transport & Traffic Intelligence Division
"""
        channel = "E_GOVERNANCE_PORTAL"

    draft_dict = {
        "id": str(uuid.uuid4()),
        "event_id": event_dict.get("id", str(uuid.uuid4())),
        "reference_no": ref_no,
        "department": dept,
        "recipient_name": recipient_name,
        "recipient_address": recipient_address,
        "subject": subject,
        "statutory_ref": statutory_ref,
        "letter_body": letter_body,
        "requested_action": requested_action,
        "priority": severity,
        "status": "DRAFT_PENDING_APPROVAL",
        "dispatch_channel": channel,
        "created_at": datetime.datetime.now().isoformat(),
        "dispatched_at": None
    }

    if db:
        new_draft = LetterDraftModel(**draft_dict)
        db.add(new_draft)
        db.commit()
        db.refresh(new_draft)

    return draft_dict
